---
version: '3.6'
networks:
  frontend:
services:
  web:
    image: 'eemechs/comments-api-dev:v1.0.0'
    restart: always
    container_name: 'comments-api'
    ports:
      - '8000:8000'
    networks:
      - frontend