---
version: '3.6'
networks:
  backend:
services:
  web:
    image: 'public.ecr.aws/f8n0u2q9/comments-api:latest'
    restart: always
    container_name: 'comments-api'
    ports:
      - '8000:8000'
    networks:
      - backend