name: 'Core Infrastructure'
on:
  push:
    paths:
      - 'dev/**'
      - .github/workflows/dev.yml
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

env:
  WORKING_DIRECTORY: './dev'
  TF_VERSION: 1.4.6
  TG_VERSION: 0.48.0

jobs:
  plan:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: ${{ env.TG_VERSION }}

      - name: 'Terragrunt Plan'
        run: terragrunt run-all plan --terragrunt-non-interactive
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          TF_TOKEN_APP_TERRAFORM_IO: '${{ secrets.TF_TOKEN_APP_TERRAFORM_IO  }}'
  
  deploy:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: ${{ env.TG_VERSION }}
      - name: 'Terragrunt Apply'
        continue-on-error: true
        run: terragrunt run-all apply --terragrunt-non-interactive
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          TF_TOKEN_APP_TERRAFORM_IO: '${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}'
