name: Docker Image CI

on:
  push:
    paths:
      - 'app/image/**'
      - .github/workflows/image-build.yml

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get Short GitHub SHA
        run: echo "SHORT_GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./app/image
          push: true
          tags: |
            eemechs/comments-api:${{ env.SHORT_GITHUB_SHA }}
            eemechs/comments-api:latest
            
