name: Docker Image CI

on:
  push:
    paths:
      - 'app/image/**'
      - .github/workflows/image-build.yml

env:
  WORKING_DIRECTORY: './app/image'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      run: |
        cd $WORKING_DIRECTORY
        IMAGE_TAG="dev"
        docker build . --file Dockerfile --tag eemechs/comments-api:$IMAGE_TAG
        echo "::set-output name=image_tag::$IMAGE_TAG"
    - name: Push the Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: eemechs/comments-api
        tag_with_ref: false
        tags: ${{ steps.build-image.outputs.image_tag }}
