name: Docker Image CI

on:
  push:
    paths:
      - 'app/image/**'
      - '.github/workflows/image-build.yml'

env:
  WORKING_DIRECTORY: './app/image'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      run: |
        cd $WORKING_DIRECTORY
        IMAGE_TAG="dev"
        docker build . --file Dockerfile --tag eemechs/comments-api:$IMAGE_TAG
        echo "::set-output name=image_tag::$IMAGE_TAG"
     
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: eemechs/comments-api:$IMAGE_TAG

